const MentorData = [
    {
        id : 1,
        name : "Dr. Manpreet Singh Manna",
        imgsrc : "images/m1.jpg",
        title : "'SWAYAM' Project Cell Incharge, Former Director 'AICTE'" ,
    },
    {
        id : 2,
        name : "Aditya Gupta",
        imgsrc : "images/m2.jpg",
        title : "Founder of 'The Rug Republic',Mountaineer",
    },
    {
        id : 3,
        name : "Dr. Ajat Shatru Arora",
        imgsrc : "images/m3.jpg",
        title : "Biomedical Engineering Expert, Dean(ACAD)SLIET",
    },
    {
        id : 4,
        name : "Parveen Kumar Purushothaman",
        imgsrc : "images/m4.jpeg",
        title : "Careers Mentor / React JS Specialist Blockchain Enthusiast ,Top 0.05% Overall in StackOverflow",
    },
    {
        id : 5,
        name : "Praveen Sharma",
        imgsrc : "images/m5.jpeg",
        title : "IT Director @CIFF, Digital Transformation andTechnology Stratergy Specialist Ex.SAM Co., EY & Infosys",
    },
    {
        id : 6,
        name : "Prateek Narang",
        imgsrc : "images/m6.jpg",
        title : "Engineer @ Google, Creator of Coding Minutes",
    },
    {
        id : 7,
        name : "Dr. Puneet Sood",
        imgsrc : "images/m7.jpeg",
        title : "Director, NIFT Kannur Kerala, Director Incharge NIFT Panchkula",
    },
    {
        id : 8,
        name : "Dr. Shalini Gupta",
        imgsrc : "images/m8.jpeg",
        title : "Founder, Principle Director of 'Desh Bhagat University' Recipient of 'Lifetime Achievement Award'",
    },
    {
        id : 9,
        name : "Yash Tiwari",
        imgsrc : "images/m9.jpg",
        title : "Global Youth Mentor, 5 TED Talks Speaker, Awarded Author of 2 Novels",
    },
    {
        id : 10,
        name : "Saurabh Trivedi",
        imgsrc : "images/m10.jpeg",
        title : "Enterpreneur, Speaker, Founder of Boudhick Ventures",
    },
    {
        id : 11,
        name : "Abhinay Bhasin",
        imgsrc : "images/m11.jpeg",
        title : "Data Scientist, Forbes 30 Under 30, VP Dentsu",
    },
    {
        id : 12,
        name : "Dr. Radhika Batra",
        imgsrc : "images/m12.jpeg",
        title : "Pediatrician, Founder & President of Every Infant Matters, Forbes Asia 30 Under 30",
    },
    {
        id : 13,
        name : "Parvesh Kumar",
        imgsrc : "images/m13.jpeg",
        title : "AR expert, Infizeal Technologies, New Delhi",
    },
    {
        id : 14,
        name : "Anmol Handa",
        imgsrc : "images/m14.jpeg",
        title : "Director, Data Science and Business Intelligence of American Express",
    },
    {
        id : 15,
        name : "Blessin George Varghese",
        imgsrc : "images/m15.jpeg",
        title : "Award Winning Tech Enthusiast, Mt Expert, Dell Campassador Season 3 Winner, Two time SIH Winner",
    },
    {
        id : 16,
        name : "Shalmali Jadhav",
        imgsrc : "images/m16.jpeg",
        title : "Founder of Empathy4You, Mental health activist.",
    },
    {
        id : 17,
        name : "Santosh Phad",
        imgsrc : "images/m17.jpeg",
        title : "Founder and Managing Trustee of Thinksharp Foundation",
    },
    {
        id : 18,
        name : "Vaibhav Shrivastava(Vayu)",
        imgsrc : "images/m18.jpg",
        title : "Bollywood Singer and Songwriter. Sony Music India",
    },
    {
        id : 19,
        name : "Piyush Gupta",
        imgsrc : "images/m19.jpg",
        title : "Building Next-Gen Carrer Assistant. Democratiing carrer Guidance and Mentorship",
    },
    {
        id : 20,
        name : "Digital Anuj",
        imgsrc : "images/m20.jpg",
        title : "Digital Marketing expert ,Founder & CEO @Digi Youth",
    },
    {
        id : 21,
        name : "Akriti Sood",
        imgsrc : "images/m21.jpeg",
        title : "Elite Top 1% of Freelancer.com Freelancer with 6  years of Experience",
    },
    {
        id : 22,
        name : "Naman Jain",
        imgsrc : "images/m22.jpeg",
        title : "Software Engineer At Bytedance Singapore",
    },
    {
        id : 23,
        name : "Ram Sharma",
        imgsrc : "images/m23.jpg",
        title : "Founding member of 'Tarraki', Charted Accountant, Public Speaker",
    },
    {
        id : 24,
        name : "Ashish Sharma",
        imgsrc : "images/m24.jpg",
        title : "Python Developer, Java and C++ Developer, Expert Wordpress Developer",
    },
    {
        id : 25,
        name : "Tatvabodh Arya",
        imgsrc : "images/m25.jpeg",
        title : "Founder of Tatva Fitness Town",
    },
    {
        id : 26,
        name : "Ashutosh Kumar",
        imgsrc : "images/m26.jpeg",
        title : "Robotics Trainer, Top-5 Performer in Dell Campassador season 4, Educational Youtuber, Social Activist",
    },
    {
        id : 27,
        name : "Ribhav Batra",
        imgsrc : "images/m27.jpeg",
        title : "Ex - Chair Person at Entrepreneurship and Devlopment cell || Former Equity Research Analyst at finalyst Partners",
    },
    {
        id : 28,
        name : "Sonica Singh",
        imgsrc : "images/m28.jpeg",
        title : "Founder of Moutjza Club of Readers & writers, Editor-in-chief at Peach Blink",
    },
    {
        id : 29,
        name : "Urvesh Thakkar",
        imgsrc : "images/m29.jpg",
        title : "Cyber Executive, R&D - Cyber Crime Helpline LLP | President at Anti Cyber Crime Society | Forensic Investigator ",
    },
    {
        id : 30,
        name : "Nikita Kapoor",
        imgsrc : "images/m30.jpg",
        title : "Founder of Peach Blink Publishers",
    },
    {
        id : 31,
        name : "Er. Ashutosh Kumar",
        imgsrc : "images/m31.jpeg",
        title : "Robotics Trainer, ATL Trainer, Educational YouTuber, AIR-5Dell Campassador Season 4",
    },
    {
        id : 32,
        name : "Rene Deceuninck",
        imgsrc : "images/m32.jpeg",
        title : "Master in BodyLanguage, Speaker at Oxford Business School, Founder at Advisory Board BNR Dubai",
    },
    {
        id : 33,
        name : "Mohit Yadav",
        imgsrc : "images/m33.jpeg",
        title : "Founder of Craw Cyber Security",
    },
    {
        id : 34,
        name : "Er. Sachin Korla",
        imgsrc : "images/t3.jpg",
        title : "Founder of InternWell, Dell India's No.1 University representative 2019",
    },
    {
        id : 35,
        name : "Soham Das",
        imgsrc : "images/m35.jpeg",
        title : "Team member @InternWell, Graphic Designer",
    },
    {
        id : 36,
        name : "Sanket Biswas",
        imgsrc : "images/m36.jpeg",
        title : "Research Assistant at Computer Vision Center.",
    },
    {
        id : 37,
        name : "Vidhi Tyagi",
        imgsrc : "images/m37.jpeg",
        title : "Musician, Lead Vocalist Zikrrtheband",
    },
    {
        id : 38,
        name : "Dr. Shailendra Jain",
        imgsrc : "images/m38.jpeg",
        title : " Director of SLIET University",
    },
    {
        id : 39,
        name : "Nidhi Kothari",
        imgsrc : "images/m39.jpeg",
        title : "Chartered Accountant with 14 years of experience An experienced trainer at HerMoneyTalks ",
    },
    {
        id : 40,
        name : "Er. Ayush Thakur",
        imgsrc : "images/m40.jpeg",
        title : "Co-Founder @InternWell, Team TheNoobDesigner, Professional Designer with experience of 3 years",
    },
    {
        id : 41,
        name : "Mohit Gupta",
        imgsrc : "images/m41.jpeg",
        title : "A Social Media influencer",
    },
    {
        id : 42,
        name : "Kartik Mathur",
        imgsrc : "images/m42.jpg",
        title : "Academics Head, Instructor and Product Engineer at Coding Blocks:",
    },
    {
        id : 43,
        name : "Pragya & Mridu Nagori",
        imgsrc : "images/m43.jpg",
        title : "Founder of Oorja the Youth Energy",
    },
    {
        id : 44,
        name : "Aishwaraya Kalro",
        imgsrc : "images/m45.jpg",
        title : "Founder of Social Pukar",
    },
    {
        id : 45,
        name : "Ankita Biswas",
        imgsrc : "images/m46.jpg",
        title : "Social media Influencer",
    },
    {
        id : 46,
        name : "Manan Verma",
        imgsrc : "images/m47.jpg",
        title : "SDE at Urban Company",
    },
    {
        id : 47,
        name : "Farrhad Acidwalla",
        imgsrc : "images/m48.jpg",
        title : "Top 10 Young Entrepreneur in India, TEDx Speaker, Founder of Rockstah Media",
    },
    {
        id : 48,
        name : "Dravisha Katoch",
        imgsrc : "images/m49.jpg",
        title : "Founder of Learn for less, TEDx Speaker",
    }
]

export default MentorData